src/Entity/Message.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Message
 *
 * @ORM\Table(name="message")
 * @ORM\Entity
 */
class Message
{
    /**
     * @var string
     *
     * @ORM\Column(name="subject", type="string", length=255, nullable=false)
     */
    private $subject;

    /**
     * @var string
     *
     * @ORM\Column(name="message", type="string", length=255, nullable=false)
     */
    private $message;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="sent_date", type="datetime", nullable=false)
     */
    private $sent_date;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var \App\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $userIdSender;

    /**
     * @var \App\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $userIdReceiver;

    /**
     * @var int
     *
     * @ORM\Column(name="conversation", type="string", nullable=false)
     */
    private $conversation;

    /**
     * @return int
     */
    public function getConversation(): string
    {
        return $this->conversation;
    }

    /**
     * @param int $conversation
     */
    public function setConversation(string $conversation): void
    {
        $this->conversation = $conversation;
    }


    /**
     * @return string
     */
    public function getSubject(): ?string
    {
        return $this->subject;
    }

    /**
     * @param string $subject
     */
    public function setSubject(string $subject): void
    {
        $this->subject = $subject;
    }

    /**
     * @return string
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * @param string $message
     */
    public function setMessage(string $message): void
    {
        $this->message = $message;
    }

    /**
     * @return \DateTime
     */
    public function getSentDate(): ?\DateTime
    {
        return $this->sent_date;
    }

    /**
     * @param \DateTime $sent_date
     */
    public function setSentDate(\DateTime $sent_date): void
    {
        $this->sent_date = $sent_date;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return User
     */
    public function getUserIdSender(): ?User
    {
        return $this->userIdSender;
    }

    /**
     * @param User $userIdSender
     */
    public function setUserIdSender(User $userIdSender): void
    {
        $this->userIdSender = $userIdSender;
    }

    /**
     * @return User
     */
    public function getUserIdReceiver(): ?User
    {
        return $this->userIdReceiver;
    }

    /**
     * @param User $userIdReceiver
     */
    public function setUserIdReceiver(User $userIdReceiver): void
    {
        $this->userIdReceiver = $userIdReceiver;
    }


}

src/Entity/Rental.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Rental
 *
 * @ORM\Table(name="rental")
 * @ORM\Entity
 */
class Rental
{

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="choice_date", type="date", length=255, nullable=false)
     */
    private $choice_date;

    /**
     * @var boolean
     *
     * @ORM\Column(name="confirmed", type="boolean", length=255, nullable=false)
     */
    private $confirmed;

    /**
     * @var integer
     *
     * @ORM\Column(name="mark", type="integer", length=255, nullable=false)
     */
    private $mark;

    /**
     * @var \App\Entity\Announce
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Announce", cascade={"remove"})
     */
    private $announce;

    /**
     * @var \App\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User", cascade={"remove"})
     */
    private $user;

    /**
     * @var \App\Entity\Disponibility
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Disponibility", cascade={"remove"})
     */
    private $disponibility;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @return \DateTime
     */
    public function getChoiceDate(): \DateTime
    {
        return $this->choice_date;
    }

    /**
     * @param \DateTime $choice_date
     */
    public function setChoiceDate(\DateTime $choice_date): void
    {
        $this->choice_date = $choice_date;
    }

    /**
     * @return bool
     */
    public function isConfirmed(): bool
    {
        return $this->confirmed;
    }

    /**
     * @param bool $confirmed
     */
    public function setConfirmed(bool $confirmed): void
    {
        $this->confirmed = $confirmed;
    }

    /**
     * @return int
     */
    public function getMark(): int
    {
        return $this->mark;
    }

    /**
     * @param int $mark
     */
    public function setMark(int $mark): void
    {
        $this->mark = $mark;
    }

    /**
     * @return Announce
     */
    public function getAnnounce(): Announce
    {
        return $this->announce;
    }

    /**
     * @param Announce $announce
     */
    public function setAnnounce(Announce $announce): void
    {
        $this->announce = $announce;
    }

    /**
     * @return User
     */
    public function getUser(): User
    {
        return $this->user;
    }

    /**
     * @param User $user
     */
    public function setUser(User $user): void
    {
        $this->user = $user;
    }

    /**
     * @return Disponibility
     */
    public function getDisponibility(): Disponibility
    {
        return $this->disponibility;
    }

    /**
     * @param Disponibility $disponibility
     */
    public function setDisponibility(Disponibility $disponibility): void
    {
        $this->disponibility = $disponibility;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }


}

templates/base.html.twig
    <!DOCTYPE html>
<html>
<head>
    <link rel="apple-touch-icon" sizes="57x57" href="{{ asset('img/favicon/apple-icon-57x57.png') }}">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ asset('img/favicon/apple-icon-60x60.png') }}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ asset('img/favicon/apple-icon-72x72.png') }}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('img/favicon/apple-icon-76x76.png') }}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ asset('img/favicon/apple-icon-114x114.png') }}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ asset('img/favicon/apple-icon-120x120.png') }}">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ asset('img/favicon/apple-icon-144x144.png') }}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ asset('img/favicon/apple-icon-152x152.png') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('img/favicon/apple-icon-180x180.png') }}">
    <link rel="icon" type="image/png" sizes="192x192" href="{{ asset('img/favicon/android-icon-192x192.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('img/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ asset('img/favicon/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('img/favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ asset('img/favicon/manifest.json') }}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{{ asset('img/favicon//ms-icon-144x144.png') }}">
    <meta name="theme-color" content="#ffffff">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Accueil{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap.min.css') }}"/>
    <script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/styles.css') }}">
    {% block css %}{% endblock %}
</head>
<body class="position-relative">
<header>
    <div class="">
        <div class="">
            <!--LOGO-->
            <div class="d-none d-md-block">
                <a href="{{ path('index') }}"><img class="img-fluid logo m-2 ml-5" src="{{ asset('img/logo.png') }}"
                                                   alt="Logo Zikaloka"/></a>
                <div class="d-none d-md-block float-right mr-4">
                    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
                        <div class="buttons_header_1">
                            {{ app.user.firstname }} | <a class="white_link" href="{{ path('fos_user_profile_show') }}">
                                Mon compte</a>
                            <a class="white_link" href="{{ path('fos_user_security_logout') }}">
                                {{ 'layout.logout'|trans({}, 'FOSUserBundle') }}
                            </a>
                        </div>
                    {% else %}
                        <div class="buttons_header_2">
                            <button type="button" class="btn white_link" data-toggle="modal"
                                    data-target="#exampleModal">
                                Connexion
                            </button>
                        </div>
                    {% endif %}
                </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                     aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Connexion</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div id="tmpmodal"></div>
                            </div>
                            <div class="modal-footer">
                                <a class="white_link"
                                   href="{{ path('fos_user_registration_register') }}">Inscription</a>
                                <a class="white_link" href="{{ path('fos_user_resetting_request') }}">Mot de passe
                                    oublié</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--2EME PARTIE : MENU-->
    <nav class="navbar navbar-light navbar-expand-md">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar"
                aria-controls="collapsingNavbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="d-md-none hidden-md" style="right: 0">
            {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
                <a class="white_link" href="{{ path('fos_user_profile_show') }}"> Mon compte</a>
                <a class="white_link" href="{{ path('fos_user_security_logout') }}">
                    {{ 'layout.logout'|trans({}, 'FOSUserBundle') }}
                </a>
            {% else %}
                <a class="white_link"
                   href="{{ path('fos_user_security_login') }}">{{ 'layout.login'|trans({}, 'FOSUserBundle') }}</a>
            {% endif %}
        </div>
        <div class="collapse navbar-collapse  justify-content-between align-items-center w-100" id="collapsingNavbar">
            <ul class="navbar-nav mx-auto text-center">
                <li class="nav-item d-md-none hidden-md">
                    <a class="nav-link" href="{{ path('index') }}">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('list_index_announce') }}">Annonces</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('add_announce') }}">Poster une annonce</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('faq') }}">Foire aux questions</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('contact_admin') }}">Contactez-nous</a>
                </li>
            </ul>
        </div>
    </nav>
    <!--    CONTENU     -->
</header>
{% block body %}

    <div class="acc_bloc_1">
        <h1>Un grand choix d'instruments et de matériel</br>disponibles en location</h1>
    </div>


    <div class="acc_bloc_2">
        <h2>ZIKALOKA, LA REFERENCE LOCATION <br><span>pour les professionnels et les particuliers</span></h2>

        <div class="container text-center">
            <div class="row">

                <div class="col-md-4">
                    <img src="{{ asset('img/elmt1.png') }}" alt="guitare"/>
                    <p>Un grand choix de location</br>pour tous les budgets</p>
                </div>

                <div class="col-md-4">
                    <img src="{{ asset('img/elmt2.png') }}" alt="shield"/>
                    <p>Un espace sécurisé</br>et des garanties</p>
                </div>

                <div class="col-md-4">
                    <img src="{{ asset('img/elmt3.png') }}" alt="form"/>
                    <p>Commencez à louer et</br>gagner de l'argent</p>
                </div>
            </div>
        </div>
    </div>


    <div class="acc_bloc_3">
        <h2>Les avis de nos utilisateurs</h2>

        <div class="container">
            <div class="commentaire-index">
                <div class="commentaire-item">
                    <p>"Zikaloka était pour moi une évidence pour proposer</br>mon matériel et mes instruments.
                        Sécurité, efficacité</br>et garantie de paiement ! Quoi de mieux ?"</p>
                    <p>Laurent P.</p>
                </div>

                <div class="commentaire-item">
                    <p>"Je souhaitais louer mes anciens instruments et j'ai</br>trouvé l'offre de Zikaloka qui me permet
                        de les</br>proposer de manière totalement sécurisée."</p>
                    <p>Laura M.</p>
                </div>
            </div>

            <div class="boutton-index text-center">
                <a href="{{ path('fos_user_registration_register') }}" class="btn white_link">Je m'inscris</a>
            </div>

        </div>
    </div>

{% endblock body %}


<!--    FOOTER     -->
<div class="espace_footer"></div>

<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-6"><p class="text-left">© Zikaloka 2018 - Tout droits réservés</p></div>
            <div class="col-sm-6"><p class="text-right"><a href="{{ path('legals') }}">Mentions Légales</a></p></div>
        </div>
    </div>
</footer>

<script type="text/javascript">
    $('#exampleModal').on('show.bs.modal', function (event) {
        $.post('{{ path('fos_user_security_login') }}', function (xx) {
            var $response = $(xx);
            $('#tmpmodal').html($response.find('form'))
        })
    })
</script>
</body>
</html>

templates/contact_admin_form.html.twig
{% extends 'base.html.twig' %}
{% block title %}Contact{% endblock %}
{% block body %}
    <div class="container col-md-6 mt-5">
        <h2>Contacter un administrateur</h2>

        {% for label, messages in app.flashes(['success', 'error']) %}
            {% for message in messages %}
                <div class="alert alert-{{ label }}">
                    {{ message }}
                </div>

            {% endfor %}
        {% endfor %}
        {{ form_start(formMessage) }}


            {{ form_row(formMessage.email, { 'attr': {'label': 'Votre adresse email','class': 'form-control'} }) }}


        {{ form_row(formMessage.subject, { 'attr': {'label': 'Sujet','class': 'form-control'} }) }}
        {{ form_row(formMessage.message, { 'attr': {'class': 'form-control'} }) }}

        {{ form_row(formMessage.save, { 'attr': {'class': 'white_link mt-4'} }) }}

        {{ form_end(formMessage) }}

    </div>
{% endblock %}

templates/contact_renter.html.twig
{% extends 'base.html.twig' %}
{% block title %}Contact{% endblock %}
{% block body %}
    <div class="container col-md-6 mt-5">
        <h1>Demande d'informations</h1>
        <p>Vous souhaitez contacter <strong>{{ user.getFirstName() ~ ' ' ~ user.getLastName() }}</strong> pour
            l'annonce <strong>{{ announce.getTitle() }}</strong> ?</p>

        {% for label, messages in app.flashes(['success', 'error']) %}
            {% for message in messages %}
                <div class="alert alert-{{ label }}">
                    {{ message }}
                </div>

            {% endfor %}
        {% endfor %}
        {{ form_start(formMessage) }}
        {{ form_row(formMessage.subject, { 'attr': {'label': 'Sujet','class': 'form-control'} }) }}
        {{ form_row(formMessage.message, { 'attr': {'class': 'form-control'} }) }}

        {{ form_row(formMessage.save, { 'attr': {'class': 'white_link mt-4'} }) }}

        {{ form_end(formMessage) }}


    </div>
{% endblock %}

templates/conversation.html.twig
{% extends 'base.html.twig' %}
{% block title %}Messages{% endblock %}
{% block css %}
    <style>

        .containers {
            background-color: #f1f1f1;
            border-radius: 5px;
            padding: 10px;
            margin: 10px 0;
            width: 80%;
        }

        .darker {
            border-radius: 5px;
            background-color: #0084ff;
            color: white;
            width: auto;
            margin-left: 20%;
        }

        .containers::after {
            content: "";
            clear: both;
            display: table;
        }

        .time-right {
            float: right;
            color: #aaa;
        }

        .time-left {
            float: left;
            color: white;
        }

        .my_announces {
            overflow: scroll;
            height: 300px;
        }
    </style> {% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 my_announces">
                {% if messages is empty %}
                    <p align="center">Aucun messages envoyés !</p>
                {% else %}


                    {% for message in messages %}
                        {% if message.userIdSender.id != app.user.id %}
                            <div class="containers">
                                <p>{{ message.message }}</p>
                                <span class="time-right">{{ message.sentDate|date('d/m/Y') }}</span>
                            </div>
                        {% else %}

                            <div class="containers darker">
                                <p>{{ message.message }}</p>
                                <span class="time-left">{{ message.sentDate|date('d/m/Y') }}</span>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}

            </div>
        </div>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>

{% endblock %}

templates/email.html.twig
{{ body }}

templates/faq.html.twig
{% extends 'base.html.twig' %}
{% block title %}Foire aux questions{% endblock %}
{% block body %}

    <div class="container mt-5 mb-5">
        <div class="faq">
            <h1 style="text-align: center">Bienvenue sur notre FAQ. Vous avez des difficultés à utiliser notre
                plateforme de location d'instruments de musique ?<br/>Une solution à votre problème se trouve
                certainement ici.</h1><br/><br/>
            <br><br>
            <h2>Vous ne savez pas comment vous inscrire ?</h2>
        </div>
        <p>Cliquez sur le boutton <strong>Connexion</strong> en haut à droite de votre page. Dans le formulaire qui
            apparaît veuillez sélectionner <strong>Inscription</strong>.
            Vous allez ensuite être redirigé sur notre formulaire d'inscription. Remplissez tous les champs demandés
            puis cliquez sur <strong>S'inscrire</strong>.</p><br/><br/>
        <br><br>
        <h2>Vous n'arrivez pas à retrouver vos identifiants ?</h2>
        <p>Cliquez sur le boutton <strong>Connexion</strong> en haut à droite de votre page. Dans le formulaire qui
            apparaît veuillez sélectionner <strong>Mot de passe oublié</strong>.
            Vous allez ensuite recevoir votre mot de passe dans votre boite mail.</p><br/><br/>
        <br><br>
        <h2>Vous souhaitez ajouter une annonce ?</h2>
        <p>Une fois que vous êtes connecté, cliquez sur <strong>Poster une annonce</strong>. Veuillez remplir tous les
            champs demandés puis cliquez sur <strong>Envoyer</strong> pour créer votre annonce.</p><br/><br/>
        <br><br>
        <h2>Vous souhaitez modifier votre compte ?</h2>
        <p>Cliquez sur le bouton <strong>Mon compte</strong> en haut de votre page, puis veuillez sélectionner le bouton
            <strong>Modifier</strong> qui se trouve en dessous de vos informations personnelles pour accéder au
            formulaire de modification d'informations.</p><br/><br/>
        <br><br>
        <h2>Vous voulez voir toutes les annonces que vous avez posté et les gérer ?</h2>
        <p>Cliquez sur le bouton <strong>Mon compte</strong> en haut de votre page, puis veuillez sélectionner le bouton
            <strong>Mes annonces</strong> qui se trouve en dessous de vos informations personnelles pour visualiser vos
            différentes annonces. Vous pourrez administrer vos annonces à partir de cette page.</p><br/><br/>
        <br><br>
        <h2>Vous souhaitez nous contacter ?</h2>
        <p>Dans le menu, nous avons ajouté le lien <strong>Contactez-nous</strong> qui vous permet de nous écrire.
            Veuillez remplir le champ <strong>Sujet</strong> et le champ <strong>Votre message</strong> puis cliquez sur
            le bouton <strong>Envoyer</strong> pour nous faire parvenir votre question.
            Nous y répondrons dans les plus brefs délais.</p>
    </div>
    </div>
{% endblock %}

templates/list_announce.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mes annonces{% endblock %}
{% block body %}

    <div class="container padding_pages">
        {% if listAnnounce is empty %}
            Aucune annonce !
        {% else %}
            <div class="row">
                <div class="col-sm-12 my_announces">
                    <h1>Mes annonces</h1>
                    <table class="table">
                        <th>Titre</th>
                        <th>Description</th>
                        <th>Prix</th>
                        <th>Etat</th>
                        <th>Outils</th>
                        {% for Announce in listAnnounce %}
                            <tr>
                                <td>{{ Announce.title }}</td>
                                <td>{{ Announce.description }}</td>
                                <td>{{ Announce.price }}€</td>
                                <td>{% if Announce.isActive is null %}
                                        En attente de validation
                                    {% elseif Announce.isActive is same as(false) %}
                                        Refusée
                                    {% else %}
                                        Validée
                                    {% endif %}
                                </td>
                                <td><a href="{{ path('edit_announce', {'id': Announce.id}) }}">Modifier</a> / <a
                                            href="{{ path('delete_announce', {'id': Announce.id}) }}">Supprimer</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        {% endif %}
        <br><br>

        <div class="text-center liste_annonces_liens">
            <a class="white_link" href="{{ path('add_announce') }}">Ajouter</a>
            <a class="white_link" href="{{ path('see_rental') }}">Réservations sur mes annonces</a>
        </div>
    </div>
{% endblock %}

templates/mail.announce.html.twig
<img src="../public/img/logo.png" alt="logo"/>
<img src="../public/img/fond-index.png" alt="fond"/>
<h1>Récapitulatif de votre annonce</h1>
{{ body }}
<div class="espace_footer"></div>
<footer>
    <div class="container">
        <p><a class="text-muted" href="{{ path('legals') }}">Mentions Légales</a></p>
        <p><a class="text-muted" href="#">www.zikaloka.com</a></p>
        <p class="text-muted text-right"><a class="text-muted" href="#">Se désinscrire</p>
    </div>
</footer>
</div>

templates/make_rent.html.twig
{% extends 'base.html.twig' %}
{% block title %}Réservation{% endblock %}
{% block body %}
    <div class="container mt-5 mb-5 col-md-6">
        <h1>Réservation</h1>
        <p>Vous souhaitez réserver pour l'annonce <strong>{{ announce.getTitle() }}</strong> ?</p>

        <div class="col-md-6">

            {% for message in app.flashes('error') %}

                <div class="alert alert-info">
                    {{ message }}
                </div>

            {% endfor %}
            {% if allDispo is empty %}
                Aucune date de disponible !
            {% else %}
            {{ form_start(form) }}
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Sélection</th>
                    <th scope="col">Date de disponibilité</th>
                </tr>
                </thead>
                <tbody>
                {% for dispo in allDispo %}
                    <tr>
                        <td>{{ form_row(attribute(form,dispo.id), { 'attr': {'class': 'form-check-input'} }) }}
                        </td>
                        {{ form_row(attribute(form,dispo.date|date("dmY")), { 'attr': {'class': 'form-check-input'} }) }}
                        <td>{{ dispo.date|date("d/m/Y") }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>


            {{ form_end(form) }}
            {% endif %}
            <a class="btn white_link" href="{{ path('show_rentals') }}">Voir mes demandes de réservations</a>

        </div>


    </div>
{% endblock %}

templates/messages.html.twig
{% extends 'base.html.twig' %}
{% block title %}Messagerie{% endblock %}
{% block body %}<br/><br/>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 my_announces">
                <h1>Messages envoyés</h1>
                {% if listMessages is empty %}
                    <p align="center">Aucun messages envoyés !</p>
                {% else %}
                    <table class="table">
                        <th>Nom</th>
                        <th>Message</th>
                        <th>Date d'envoi</th>

                        {% for message in listMessages %}
                            <tr>
                                <td>{{ message.userIdSender.firstname }} {{ message.userIdSender.lastname }}</td>
                                <td>
                                    <a href="{{ path('message', {'id': message.conversation }) }}">{{ message.message }}</a>

                                </td>
                                <td>{{ message.sentDate|date('d/m/Y') }}</td>

                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/show_rent_announces.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mes demandes{% endblock %}
{% block body %}
    <div class="container mt-5 mb-5">
        <h1 class="mb-4">Suivi des demandes de réservations</h1>


        <div class="col-md-12">
            {% if userRentals is empty %}
                Aucune annonce !
            {% else %}
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Annonce</th>
                        <th scope="col">Loueur</th>
                        <th scope="col">Dates réservés</th>
                        <th scope="col">Confirmé</th>
                        <th scope="col">Note</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in userRentals %}
                        <tr>
                            <td>
                                <a href="{{ path('show_announce', {'id': item.announce.id}) }}"> {{ item.announce.title }}</a>
                            </td>
                            <td>{{ item.announce.user }}</td>
                            <td>{{ item.choiceDate|date('d/m/Y') }}</td>
                            <td>{% if item.confirmed %}Oui{% else %}Non{% endif %}</td>
                            <td>{% if item.mark == true %}{{ item.mark }}/5{% else %}{% if item.confirmed %}<a href="{{ path('mark_show', {id: item.announce.id}) }}">Noter</a> {% else %}-{% endif %}{% endif %}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>


    </div>
{% endblock %}